config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates_uniqueness_of :movie_id,  { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates_presence_of :overview
  validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :destroy]

  def index
    @bookmarks = Bookmark.all
  end

  def show
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to bookmark_path(@bookmark), stauts: :see_other
  end

  private



  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:edit, :show, :update]

  def index
    @lists = List.all
  end

  def show; end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  def destroy
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating, :trailer)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit class: 'btn-submit mt-3' %>
<% end %>

app/views/bookmarks/_header.html.erb
<div class="banner-container banner-change">
  <div class="banner-nav-bar">
    <div><h1><i class="fas fa-play"></i>Watch List</h1></div>
    <div>
      <ul class="banner-ul">
        <li>Login</li>
        <li class="btn-sign">Sign up</li>
      </ul>
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
<%= render 'header' %>

<div class="container">
  <div class="">
    <div class="row new-form">
      <div class="col-lg-6 left-bg-list">
      </div>
      <div class="col-lg-6 right-bg" >
        <%= render 'form', bookmark: @bookmark %>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_footer.hmtl.erb
<div class="container">
  <p>Check this project on my <a href="https://github.com/thiagohrcosta/rails-watch-list" target="_blank"><i class="fab fa-github"></i></a> github.</p>
</div>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.submit class: 'btn-submit-movie mt-3' %>
<% end %>

app/views/lists/_header.html.erb
<div class="banner-container banner-change">
  <div class="banner-nav-bar">
    <div><h1><i class="fas fa-play"></i>Watch List</h1></div>
    <div>
      <ul class="banner-ul">
        <li>Login</li>
        <li class="btn-sign">Sign up</li>
      </ul>
    </div>
  </div>
</div>

app/views/lists/edit.html.erb
<%= render 'header' %>

<div class="container">
  <div class="">
    <div class="row new-form">
      <div class="col-lg-6 left-bg-list">
      </div>
      <div class="col-lg-6 right-bg" >
        <%= render 'form', list: @list %>
      </div>
    </div>
  </div>

</div>

app/views/lists/index.html.erb
<div class="banner-container">
  <div class="banner-nav-bar">
    <div><h1><i class="fas fa-play"></i><span class="logo-title">Watch List</span></h1></div>
    <div>
      <ul class="banner-ul">
        <li>Login</li>
        <li class="btn-sign">Sign up</li>
      </ul>
    </div>
  </div>

  <div class="banner-info">
    <div>
      <p class="banner-title">AVENGERS COLLECTION</p>
      <p class="banner-subtitle">All movies avaiable right now!</p>
      <div class="btn-infos">
<!--         <p class="btn-add">Add to list</p> -->
        <p class="btn-add"><%= link_to "Add movie", new_movie_path(@movie) %></p>
        <p class="btn-more-info"><%= link_to "Add list", new_list_path(@bookmark) %></p>
      </div>
    </div>
  </div>
</div>

<div class="movie-category">
  <p class="category-title">MY LISTS</p>
</div>

<div class="container">

<div class="lists">
  <% @lists.each do |list| %>
  <div class="left-border">

    <div>
      <div class="list-box">
        <div class="row">
          <div class="col-lg-6">
          </div>
          <div class="col-lg-6">
            <h3 class="list-title"><%= list.name %> List</h3>
            <p class="click-text-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac interdum tellus. </p>
            <span class="click">
              <%= link_to "More info", list_path(list), class:"btn-click"%>
            </span>

          </div>
        </div>
      </div>

    </div>
  </div>
  <% end %>
</div>

</div>

app/views/lists/new.html.erb
<%= render 'header' %>

<div class="container">
  <div class="">
    <div class="row new-form">
      <div class="col-lg-6 left-bg-list">
      </div>
      <div class="col-lg-6 right-bg" >
        <%= render 'form', list: @list %>
      </div>
    </div>
  </div>

</div>

app/views/lists/show.html.erb
<%= render 'header' %>

<div class="container">
  <div class="movie-content">
    <div class="row">
      <div class="col-lg-6">
      <div class="col-lg-6">
        <h2><%= @list.name %> Movies</h2>
        <div class="btn-style">
          <p><%= link_to "Bookmark",  new_list_bookmark_path(@list), class: 'btn-book' %></p>
          <p><%= link_to "Edit", edit_list_path(@list), class: 'btn-edit' %></p>
          <p><%= link_to "Delete", edit_list_path(@list), class: 'btn-delete' %></p>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac interdum tellus. Ut sed nibh ornare, ultrices lorem nec, tempus quam. Aliquam vitae nulla sit amet erat lacinia eleifend ut vitae lectus.</p>
      </div>
    </div>

    <hr>


    <div class="movies-grid">
      <% @list.movies.each do |movie| %>
      <div class="box-poster">
        <img class="img-poster" src="<%= movie.poster_url %>">
        <p class="movie-path"><%= link_to movie.title, movie_path(movie) %></p>
      </div>
      <% end %>
    </div>

  </div>



</div>

app/views/movies/_form.html.erb
<%= simple_form_for(movie) do |f| %>
  <%= f.input :title %>
  <%= f.input :rating %>
  <%= f.input :overview %>
  <%= f.input :poster_url %>
  <%= f.submit class: 'btn-submit-movie mt-3' %>
<% end %>

app/views/movies/_header.html.erb
<div class="banner-container banner-change">
  <div class="banner-nav-bar">
    <div><h1><i class="fas fa-play"></i>Watch List</h1></div>
    <div>
      <ul class="banner-ul">
        <li>Login</li>
        <li class="btn-sign">Sign up</li>
      </ul>
    </div>
  </div>
</div>

app/views/movies/edit.html.erb
<%= render 'header' %>

<div class="container">
  <div class="">
    <div class="row new-form">
      <div class="col-lg-6 left-bg-new">
      </div>
      <div class="col-lg-6 right-bg" >
        <%= render 'form', movie: @movie %>
      </div>
    </div>
  </div>

</div>

app/views/movies/new.html.erb
<%= render 'header' %>

<div class="container">
  <div class="">
    <div class="row new-form">
      <div class="col-lg-6 left-bg-new">
      </div>
      <div class="col-lg-6 right-bg" >
        <%= render 'form', movie: @movie %>
      </div>
    </div>
  </div>

</div>

app/views/movies/show.html.erb
<%= render 'header' %>

<div class="container">
  <div class="row movie-display">
    <div class="col-lg-6">
      <img class="img-display-poster" src="<%= @movie.poster_url %>" >
    </div>
    <div class="col-lg-6 movie-display-content">
      <div class="movie-header-content">
        <p class="movie-title"><%= @movie.title %></p>
        <p class="btn-movie-edit"><%= link_to "Edit movie", edit_movie_path(@movie) %></p>
      </div>

      <div>
        <p><span class="movie-rating"><%= @movie.rating %></span></p>
      </div>

        <p>
          <%= @movie.overview %>
        </p>

    </div>
  </div>
</div>